TICKERS = [
    "ABVX","AAP","ADMA","AGEN","CELC","CNC","CONI","DAVE","FIVN","GLUE",
    "LUMN","LWAY","MGPI","NNNN","NVCR","NVDL","ODD","PEGA","QURE","RXO",
    "SBUX","SERV","SOGP","TIL","TREE","UPST","WLDN","ZEPP"
]

DEFAULT_INTERVAL = "1d"
DEFAULT_PERIOD = "5y"

DATA_SOURCE_ENV = "DATA_SOURCE"
POLYGON_API_KEY_ENV = "POLYGON_API_KEY"
